//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorMonografia
    {
        public int Id { get; set; }
        public int IdAutor { get; set; }
        public int IdMonografia { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Monografia Monografia { get; set; }
    }
}
